### ISSUE TITLE
Jenvtest server startup error

### ISSUE THREAD

**Issue by gyfora** [java-operator-sdk/jenvtest#105]
I am trying a very minimal test example:

```
import io.fabric8.kubernetes.client.KubernetesClient;
import io.javaoperatorsdk.jenvtest.junit.EnableKubeAPIServer;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;


@EnableKubeAPIServer
public class JenvTest {

    static KubernetesClient client;

    @Test
    public void simpleTest() {
        assertFalse(client.configMaps().list().getItems().isEmpty());
    }
}
```

However the test fails with the following error after exactly 1 minute:

```
io.javaoperatorsdk.jenvtest.JenvtestException: Kube API Server did not start properly

	at io.javaoperatorsdk.jenvtest.process.ProcessReadinessChecker.pollWithTimeout(ProcessReadinessChecker.java:81)
	at io.javaoperatorsdk.jenvtest.process.ProcessReadinessChecker.waitUntilDefaultNamespaceAvailable(ProcessReadinessChecker.java:42)
	at io.javaoperatorsdk.jenvtest.process.KubeAPIServerProcess.waitUntilReady(KubeAPIServerProcess.java:94)
	at io.javaoperatorsdk.jenvtest.KubeAPIServer.start(KubeAPIServer.java:48)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.startApiServer(KubeAPIServerExtension.java:85)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.lambda$startIfAnnotationPresent$2(KubeAPIServerExtension.java:78)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.lambda$startIfAnnotationPresent$3(KubeAPIServerExtension.java:71)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.startIfAnnotationPresent(KubeAPIServerExtension.java:68)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.initialize(KubeAPIServerExtension.java:61)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.beforeAll(KubeAPIServerExtension.java:37)
```

Full logs:
https://gist.github.com/gyfora/f1aa0e26620e5991b1800776d936315c

I wonder if this could be some networking related issue because based on the logs the server actually seems to start but the readiness check fails.

System info:
Apple M1 Max
JDK 11

**Comment by gyfora** [comment]
cc @csviri

**Comment by csviri** [comment]
this might be related to this issue: https://github.com/java-operator-sdk/jenvtest/pull/133

@gyfora  could you retest it pls with the newest release?

**Comment by gyfora** [comment]
I tested with the most recent version and it works perfectly! Closing this ticket thank you :)
