### ISSUE TITLE
jenvtest-fabric8-client-support fails in projects with newer fabric8 client

### ISSUE THREAD

**Issue by BramMeerten** [java-operator-sdk/jenvtest#117]
I have a project with fabric8 dependency version `6.8.1`. When I have the `jenvtest-fabric8-client-support` dependency and run a test, I get the following error:
```
java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/dsl/ParameterNamespaceListVisitFromServerGetDeleteRecreateWaitApplicable

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:80)
	at io.javaoperatorsdk.jenvtest.junit.Fabric8ClientInjectionHandler.setKubernetesClientToField(Fabric8ClientInjectionHandler.java:38)
	at io.javaoperatorsdk.jenvtest.junit.Fabric8ClientInjectionHandler.inject(Fabric8ClientInjectionHandler.java:29)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.lambda$initialize$1(KubeAPIServerExtension.java:63)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.initialize(KubeAPIServerExtension.java:63)
	at io.javaoperatorsdk.jenvtest.junit.KubeAPIServerExtension.beforeAll(KubeAPIServerExtension.java:37)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
[...]
```

This is caused by a breaking change in [version 6.7.0](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.7.0), in [fix 4662](https://github.com/fabric8io/kubernetes-client/pull/4662) the class was removed.

This is probably fixed by upgrading fabric8.

**Comment by csviri** [comment]
Hi updated fabric8 for 6.9.2 (newest) hope that helps, will close this issue, pls reopen if it not works after the release.
